# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 23:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180804_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novasenha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_acesso',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'M\xe9dio'), ('Alto', 'Alto')], default='baixo', max_length=6),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='descricao',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est\xe1 ativo?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='\xc9 admin'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo', to='accounts.Titulo', verbose_name='Titula\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'o nome de usu\xe1rio s\xf3 pode conter letras, digitos os os seguintes caracteres @ . + - _', 'invalid')], verbose_name='Nome do Usu\xe1rio'),
        ),
    ]
