# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-22 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name=b'T\xc3\xadtulo')),
                ('keywords', models.CharField(max_length=150, verbose_name=b'Palavras Chaves')),
                ('autor', models.CharField(max_length=150, verbose_name=b'Autor')),
                ('co_orientador', models.CharField(blank=True, max_length=150, verbose_name=b'Co Orientador')),
                ('resumo', models.TextField(blank=True, verbose_name=b'Resumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=b'Atualizado em')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to=settings.AUTH_USER_MODEL, verbose_name=b'orientador')),
            ],
        ),
    ]
