# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhos',
            name='pdf_trabalho',
            field=models.FileField(blank=True, null=True, upload_to='trabalhos/media'),
        ),
        migrations.AlterField(
            model_name='defesatrabalho',
            name='status',
            field=models.CharField(choices=[('pendente_banca_avaliadora', 'Aguardando reposta confirma\xe7\xe3o dos avaliadores'), ('agendado', 'Agendado')], default='pendente_banca_avaliadora', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='defesatrabalho',
            name='trabalho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabalhos.Trabalhos', verbose_name='trabalho'),
        ),
        migrations.AlterField(
            model_name='trabalhos',
            name='banca',
            field=models.ManyToManyField(related_name='bancas', through='trabalhos.BancaTrabalho', to=settings.AUTH_USER_MODEL),
        ),
    ]
