# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefesaTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=250, verbose_name=b'Local')),
                ('data', models.DateField(blank=True, null=True, verbose_name=b'Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name=b'Hor\xc3\xa1rio')),
                ('status', models.CharField(choices=[(b'pendente_banca_avaliadora', b'Aguardando reposta ao convite para banca'), (b'agendado', b'Agendado')], max_length=30, verbose_name=b'Status')),
                ('banca', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='trabalhos',
            name='autor',
            field=models.CharField(max_length=250, verbose_name=b'Autor'),
        ),
        migrations.AlterField(
            model_name='trabalhos',
            name='co_orientador',
            field=models.CharField(blank=True, max_length=250, verbose_name=b'Co Orientador'),
        ),
        migrations.AlterField(
            model_name='trabalhos',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name=b'T\xc3\xadtulo'),
        ),
        migrations.AddField(
            model_name='defesatrabalho',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='trabalhos.Trabalhos', verbose_name=b'trabalho'),
        ),
    ]
