# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defesatrabalho',
            name='trabalho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bancatrabalhos', to='trabalhos.Trabalhos', verbose_name='trabalho'),
        ),
    ]
