# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0002_auto_20180930_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defesatrabalho',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='defesatrabalho',
            name='hora',
            field=models.TimeField(verbose_name='Hor\xe1rio'),
        ),
        migrations.AlterField(
            model_name='defesatrabalho',
            name='status',
            field=models.CharField(choices=[('pendente_banca_avaliadora', 'Aguardando reposta ao convite para banca'), ('agendado', 'Agendado')], default='pendente_banca_avaliadora', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trabalhos',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='T\xedtulo'),
        ),
    ]
